/**
 * Generates one printable QR code per active table (FR-W1: each table's QR
 * encodes the full URL of its generated `/t/<code>/` page) plus an HTML
 * sheet for printing them all at once.
 *
 * Usage:
 *   pnpm generate-qr
 *   QR_BASE_URL=http://localhost:5173 pnpm generate-qr   # point at a local build
 */
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import QRCode from "qrcode";
import { getActiveTables, type Table } from "@game-master-bell/shared";

// Matches the GitHub Pages project site (apps/bell-web/vite.config.ts `base`)
// and the per-table routes generated by apps/bell-web/scripts/generate-table-pages.mjs.
const DEFAULT_BASE_URL = "https://gatherloop.github.io/game-master-bell";

const baseUrl = (process.env.QR_BASE_URL ?? DEFAULT_BASE_URL).replace(/\/+$/, "");
const outDir = join(dirname(fileURLToPath(import.meta.url)), "..", "qr-codes");

function tableUrl(table: Table): string {
  return `${baseUrl}/t/${table.code}/`;
}

function escapeHtml(value: string): string {
  return value.replace(/[&<>"']/g, (char) => {
    switch (char) {
      case "&":
        return "&amp;";
      case "<":
        return "&lt;";
      case ">":
        return "&gt;";
      case '"':
        return "&quot;";
      default:
        return "&#39;";
    }
  });
}

function printSheetHtml(tables: Table[]): string {
  const cards = tables
    .map(
      (table) => `
      <figure class="card">
        <img src="${table.code}.png" alt="Kode QR ${escapeHtml(table.displayName)}" />
        <figcaption>
          <strong>${escapeHtml(table.displayName)}</strong>
          <span>Lantai ${table.floor}</span>
        </figcaption>
      </figure>`,
    )
    .join("\n");

  return `<!doctype html>
<html lang="id">
  <head>
    <meta charset="UTF-8" />
    <title>Kode QR Game Master Bell</title>
    <style>
      body {
        font-family: system-ui, sans-serif;
        margin: 1.5rem;
      }
      .grid {
        display: grid;
        grid-template-columns: repeat(3, 1fr);
        gap: 1.5rem;
      }
      .card {
        margin: 0;
        padding: 1rem;
        border: 1px solid #ddd;
        border-radius: 0.5rem;
        text-align: center;
        break-inside: avoid;
      }
      .card img {
        width: 100%;
        height: auto;
      }
      figcaption {
        display: flex;
        flex-direction: column;
        margin-top: 0.5rem;
      }
      figcaption span {
        color: #756a54;
        font-size: 0.85rem;
      }
      @media print {
        .card {
          border-color: #999;
        }
      }
    </style>
  </head>
  <body>
    <h1>Kode QR Game Master Bell</h1>
    <p>Tempel di setiap meja sesuai label. Dicetak dari ${tables.length} meja aktif.</p>
    <div class="grid">
      ${cards}
    </div>
  </body>
</html>
`;
}

async function main() {
  const tables = getActiveTables();
  await mkdir(outDir, { recursive: true });

  for (const table of tables) {
    const url = tableUrl(table);
    await QRCode.toFile(join(outDir, `${table.code}.png`), url, {
      width: 512,
      margin: 2,
      color: { dark: "#1f1a12", light: "#fffaf0" },
    });
    console.log(`${table.displayName.padEnd(12)} ${table.code.padEnd(8)} -> ${url}`);
  }

  await writeFile(join(outDir, "print-sheet.html"), printSheetHtml(tables));

  console.log(`\nGenerated ${tables.length} QR code(s) and print-sheet.html in ${outDir}`);
}

main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
